import cscl.lib.edu.rit.ds.RemoteEvent;

/**
 * Class MessageEvent encapsulates a remote event generated by a Microblog in
 * the project. The microblog events are used to report if a message is added to
 * the microblog.
 * 
 * Reference : P2Pedia version 2, Distributed Systems, Prof. Alan Kaminsky,
 * Department of Computer Science, Rochester Institute of Technology. <BR>
 * URL : http://www.cs.rit.edu/~ark/730/p2pedia02/java2html.php?file=4
 */
public class MessageEvent extends RemoteEvent {

	/** The message. */
	private Message message;

	/**
	 * Instantiates a new message event.
	 * 
	 * @param message
	 *            the message
	 * @param blogName
	 *            the blog name
	 */
	public MessageEvent(Message message) {
		this.message = message;
	}

	/**
	 * Gets the message.
	 * 
	 * @return the message
	 */
	public Message getMessage() {
		return message;
	}

}
